### ISSUE TITLE
Issues about ES

### ISSUE THREAD

**Issue by hyduez** [kaname-png/revoltx#33]
# Index
I have several mishaps when trying to initialize my bot with RevoltX, specifically 2; `ERR_REQUIRE_ESM` and the `baseDirectory` path. My specs are:

- Win32
- Yarn 3.2.0 (Berry)
- RevoltX@next
- Revolt.JS@6.0.0-rc.21

## ERR_REQUIRE_ESM
![](https://cdn.upload.systems/uploads/wC1W4WiG.png)
I get errors related to unsupported ES imports, which are apparently internal. I'm more than sure they affect more than just sending a message to the console, and a bit of that is responsible for my second snag. By the way, it's several errors related to this in different files in the package, it's not just the one in the image.

## baseDirectory
I have specified the parent path of my application as in the example [README.md](https://github.com/kaname-png/revoltx/#-folder-structure), obviously oriented to my code structure, but it does not read the `commands` folder; in it I have 2 files with their own classes exported with the `run` method. The client connects, but the integrated handler of the framework does not read the `commands`.
![](https://cdn.upload.systems/uploads/mc6GSSGs.png)

**Comment by hyduez** [comment]
> Hello, try to use the English language so that everyone can understand the problems. :)
> 
> About your error, that's because you are not using ESM in your project, you have to make your project use ESM, you can follow this guide:
> 
> https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

Thank you. But it still doesn't read the files in my commands directory. I have checked the value returned by the join() method and it is correct. Any solution?

**Comment by kaname-png** [comment]
@hyduez What is your bot directory structure?

**Comment by hyduez** [comment]
> @hyduez What is your bot directory structure?

```
| commands/
| | ping.ts
| lib/
| | client.ts
| index.ts
```

**Comment by kaname-png** [comment]
can you put in your code `container.stores.get('commands').size` after the `await login()` method in your bot?

**Comment by hyduez** [comment]
> container.stores.get('commands').size

Returns 1, that means it detects the command, right?
![](https://cdn.upload.systems/uploads/IKHSmpzz.png)

**Comment by kaname-png** [comment]
Yeah, That means that revoltx is registering your commands, now do this, in your command put a `console.log` at the start of the `run method` to see if the command is executed correctly, if it is, it means that there is an error in the code of your command.

To see if there are errors in your commands you have to set `loadDefaultErrorsListeners` to true in the client options, I see that by default it is not true, I will correct that right now.

**Comment by hyduez** [comment]
> Yeah, That means that revoltx is registering your commands, now do this, in your command put a `console.log` at the start of the `run method` Or create an event with the name `commandAccepted` to see if the command is executed correctly, if it is, it means that there is an error in the code of your command.
> 
> To see if there are errors in your commands you have to set `loadDefaultErrorsListeners` to true in the client options, I see that by default it is not true, I will correct that right now.

It just doesn't react
![](https://cdn.upload.systems/uploads/LMTpSHCS.png)
![](https://cdn.upload.systems/uploads/bmhKjo7c.png)

**Comment by kaname-png** [comment]
Is your bot open source, so I can test it myself.

**Comment by hyduez** [comment]
> Is your bot open source, so I can test it myself.
> 
> EDIT: I see that it is a problem when verifying the command in the special listeners for the command handler, I will fix it right now.

I just created a [repository](https://github.com/hyduez/fumo-revolt) with all the code, I hope you can find my mistake and save me. Thanks

**Comment by kaname-png** [comment]
Currently revolt.js has a bug with permissions, that's why the commands don't work because the bot fails to validate the permissions before executing the command.

I recommend you to use the stable version for now, when revolt.js fixes this bug the commands should work normally.

Don't worry, there are not many changes between next and stable version.
